### ISSUE TITLE
Remove Eos and Raven

### ISSUE THREAD

**Issue by NiGhTTraX** [NiGhTTraX/Tengu#1]
Remove Eos and Raven from Tengu and move them into a separate server with which Tengu will communicate when creating/editing fits.
### TODO
- [x] Remove Eos and Raven.
- [ ] Mock any existing interactions with Eos/Raven.
- [x] Remove the `cache` app.
- [x] Remove any Eos/Raven/cache specific models.
- [ ] Remove any dependence on data created by Eos.
