### ISSUE TITLE
Refactor the market tree

### ISSUE THREAD

**Issue by NiGhTTraX** [NiGhTTraX/Tengu#15]
## Need

``` gherkin
As a developer
I want a solid framework
So that I can implement stuff faster.
```
## Deliverables
- [ ] The `items_box`, `market_tree` and `market_header` logic is merged.
- [ ] Implement the state pattern.
## Solution

Refactor the entire market tree and items box logic.
#### Prerequisites
- [State pattern](http://en.wikipedia.org/wiki/State_pattern)
#### TODO

Refactor building the market tree.
- [x] move the code out of utils
- [x] turn into a view
- [ ] test it

Refactor displaying the market tree.
- [ ] merge `market_tree`, `market_header` and `items_box`
- [x] remove template tags
- [x] request the browser via ajax
- [ ] loading animation
- [ ] move resize handler logic
- [ ] test it

Refactor selecting market groups.
- [ ] state pattern
- [ ] test it

Refactor search.
- [ ] state pattern
- [ ] test it
