### ISSUE TITLE
Convert tabs to spaces

### ISSUE THREAD

**Issue by NiGhTTraX** [NiGhTTraX/Tengu#17]
## Need

``` gherkin
As a developer
I want spaces instead of tabs
So that my code is clean and visually pleasing.
```
## Solution

Convert all tabs into spaces.
#### Prerequisites
- [Google JavaScript Style Guide](https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml)
- [Google HTML/CSS Style Guide](https://google-styleguide.googlecode.com/svn/trunk/htmlcssguide.xml)
#### TODO
- [ ] vimrc options for JS: expandtabs, 4 spaces,
- [ ] vimrc options for CSS: expandtabs, 2 spaces,
- [ ] expand tabs in JS files,
- [ ] expand tabs in CSS files.
