### ISSUE TITLE
Design fit database model

### ISSUE THREAD

**Issue by NiGhTTraX** [NiGhTTraX/Tengu#2]
There should be privacy settings for the fit:
- Private. Only the owner can access it.
- Anyone with the link. Will appear in the Shared with me tab.
- Public. Will appear in search.

There should also be Corporation and Alliance settings. Figure out if these should also be in the above settings or a separate setting.

The model should have a ManyToMany field for the modules. It should look something like:

```
| fitID | rack | slot | typeID | charge | status |
```

Charge will be the typeID of the loaded charge.
Status can be one of the following:
- Online
- Offline
- Overheated

The fit should be versionable. Each edit should be a separate commit.
### Prerequisites.
- [django-reversion](https://github.com/etianen/django-reversion)
### TODO
- [ ] Implement Private/Link/Public privacy settings.
- [ ] Design Corporation/Alliance privacy settings.
- [ ] Design the Shared with me tab.
- [ ] Show the current version of the fit.
- [ ] Undo changes.
- [ ] Fork a fit.
