### ISSUE TITLE
Switch back to python 2 and MySQL

### ISSUE THREAD

**Issue by NiGhTTraX** [NiGhTTraX/Tengu#4]
Eos forced us to work with python 3 which created a few problems. One of them is the lack of proper MySQL bindings. This forced us to use sqlite, which in turn caused slower performances.
## Need

``` gherkin
As a developer
I want to use python 2
So I'm not restricted to certain py3 packages.
```

``` gherkin
As a developer
I want to use MySQL
So that I can make faster queries
And scale better.
```
## Solution

Remove Eos and Raven.
#### TODO
- [ ] Check syntax for py3 only features.
- [ ] Remove sqlite database.
- [ ] Switch to MySQL.
- [ ] Stop using our experimental branch of Django which contains necessary sqlite fixes.
